export const IMAGES = {
  app_icon: require("../../assets/app/icon-app.png"),
  email: require("../../assets/sign/email.png"),
  email_: require("../../assets/sign/email-.png"),
  lock: require("../../assets/sign/lock.png"),
  lock_: require("../../assets/sign/lock-.png"),
  user: require("../../assets/sign/user.png"),
  user_: require("../../assets/sign/user-.png"),
  eye: require("../../assets/sign/eye.png"),
  eye_: require("../../assets/sign/eye-.png"),
  gallery: require("../../assets/sign/gallery.png"),
  galleryOpt: require("../../assets/sign/galleryOpt.png"),
  cameraOpt: require("../../assets/sign/cameraOpt.png"),
  menu: require("../../assets/header/menu.png"),
  personImage: require("../../assets/util/1.jpg"),
  dots: require("../../assets/header/dots.png"),
};
